# Generated by Django 2.2 on 2019-08-30 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propiedades2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('ground_surface', models.CharField(blank=True, max_length=100, null=True)),
                ('square_m_build', models.CharField(blank=True, max_length=100, null=True)),
                ('e_construction_m', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_n', models.PositiveIntegerField(blank=True, null=True)),
                ('n_building_permit', models.PositiveIntegerField(blank=True, null=True)),
                ('value_land', models.CharField(blank=True, max_length=100, null=True)),
                ('value_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('acquiring_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.DocumentTypeC')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.Location')),
                ('property_use', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.Property')),
            ],
            options={
                'verbose_name': 'historical rent',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAcquisition',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('acquisition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('writing_data', models.CharField(choices=[('COM', 'Compraventa'), ('DON', 'Donación'), ('SUB', 'Subdivisión'), ('Otro', 'Otro')], max_length=5)),
                ('number_AASI', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('SII', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.SiiRecord')),
                ('arquitecture', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.ArchitectureRecordAcq')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('internal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.InternalAccountantsAcq')),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.Location')),
                ('notary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.NotaryAcquisition')),
                ('property_use', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.Property')),
            ],
            options={
                'verbose_name': 'historical acquisition',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
