# Generated by Django 2.2 on 2019-08-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0002_historicalacquisition_historicalrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrent',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='historicalrent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalrent',
            name='property_use',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='HistoricalAcquisition',
        ),
        migrations.DeleteModel(
            name='HistoricalRent',
        ),
    ]
