# Generated by Django 2.2 on 2019-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0005_change_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_property',
            name='comment',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalRent',
        ),
    ]
