# Generated by Django 2.2 on 2019-09-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0008_auto_20190913_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('complete', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='stats_rent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Stats'),
            preserve_default=False,
        ),
    ]
