# Generated by Django 2.2 on 2019-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0009_auto_20190916_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='complete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
