# Generated by Django 2.2 on 2019-09-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0010_auto_20190917_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='stats_rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Stats'),
        ),
    ]
