# Generated by Django 2.2 on 2019-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0011_auto_20190917_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='percentage',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
