# Generated by Django 2.2 on 2019-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0013_auto_20190924_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='district',
        ),
        migrations.RemoveField(
            model_name='historicalacquisition',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='district',
        ),
    ]
