# Generated by Django 2.2 on 2019-09-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0014_auto_20190924_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
