# Generated by Django 2.2 on 2019-09-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0015_auto_20190924_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalacquisition',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.District'),
        ),
    ]
