# Generated by Django 2.2 on 2019-10-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0016_auto_20190924_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='stats_acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Stats'),
        ),
        migrations.AddField(
            model_name='historicalacquisition',
            name='stats_acquisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propiedades2.Stats'),
        ),
    ]
