# Generated by Django 2.2 on 2019-11-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='duration',
        ),
    ]
