# Generated by Django 2.2 on 2019-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
