# Generated by Django 2.2 on 2019-11-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0022_auto_20191123_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostAcquisition', to='propiedades2.Acquisition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostRent', to='propiedades2.Rent'),
        ),
    ]
