# Generated by Django 2.2 on 2019-12-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0023_auto_20191123_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_property',
            field=models.CharField(choices=[('AC', 'Acquisition'), ('RT', 'Rent')], max_length=2),
        ),
    ]
