# Generated by Django 2.2 on 2019-12-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0024_auto_20191206_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='SII',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SII_acq', to='propiedades2.SiiRecord'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='arquitecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquitecture_acq', to='propiedades2.ArchitectureRecordAcq'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.District'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='internal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_acq', to='propiedades2.InternalAccountantsAcq'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Location'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='notary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notary_acq', to='propiedades2.NotaryAcquisition'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='property_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Property'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='stats_acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Stats'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='blueprints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planos', to='propiedades2.DocumentBlue'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='building_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PerEdificacion', to='propiedades2.DocumentBuildP'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='certified_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NumCertificado', to='propiedades2.DocumentCn'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='cip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cip', to='propiedades2.DocumentCip'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='expropriation_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ExMunicipalidad', to='propiedades2.DocumentEx'),
        ),
        migrations.AlterField(
            model_name='architecturerecordacq',
            name='municipal_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RecMunicipal', to='propiedades2.DocumentMR'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Post'),
        ),
        migrations.AlterField(
            model_name='internalaccountantsacq',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TipoContratoAdquisicion', to='propiedades2.DocumentTypeC'),
        ),
        migrations.AlterField(
            model_name='internalaccountantsacq',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Otros', to='propiedades2.DocumentOther'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Region'),
        ),
        migrations.AlterField(
            model_name='notaryacquisition',
            name='domain_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CertificadoDominio', to='propiedades2.DocumentDC'),
        ),
        migrations.AlterField(
            model_name='notaryacquisition',
            name='expropriation_serviu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serviu', to='propiedades2.DocumentEs'),
        ),
        migrations.AlterField(
            model_name='notaryacquisition',
            name='prohibitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Prohibiciones', to='propiedades2.DocumentPH'),
        ),
        migrations.AlterField(
            model_name='notaryacquisition',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Escritura', to='propiedades2.DocumentWR'),
        ),
        migrations.AlterField(
            model_name='post',
            name='acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PostAcquisition', to='propiedades2.Acquisition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PostRent', to='propiedades2.Rent'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='contract_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoContratoArriendo', to='propiedades2.DocumentTypeC'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.District'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Location'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Property'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='stats_rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='propiedades2.Stats'),
        ),
        migrations.AlterField(
            model_name='siirecord',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CerAvaluo', to='propiedades2.DocumentAc'),
        ),
        migrations.AlterField(
            model_name='siirecord',
            name='debt_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CerNoDeuda', to='propiedades2.DocumentDB'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
