# Generated by Django 2.2 on 2019-12-12 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0026_auto_20191212_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='username_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
