# Generated by Django 2.2 on 2019-12-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0028_auto_20191212_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostRent', to='propiedades2.Rent'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='contract_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoArriendo', to='propiedades2.DocumentTypeC'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='stats_rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Stats'),
        ),
    ]
